package com.youmai.hxsdk.socket;

public enum IMContentType {
    CONTENT_DEFAULT,
    CONTENT_TEXT,
    CONTENT_IMAGE,
    CONTENT_URL,
    CONTENT_VOICE,
    CONTENT_VIDEO,
    CONTENT_FILE,
    CONTENT_AT,
    CONTENT_TOPIC,
    CONTENT_PHONE,
    CONTEXT_SESSIONID,
    CONTEXT_MSGID,
    CONTEXT_PICTURE_ID,
    CONTEXT_AUDIO_ID,
    CONTEXT_VIDEO_ID,

    CONTEXT_TITLE,
    CONTEXT_DESCRIBE,
    CONTEXT_LONGITUDE,
    CONTEXT_LAITUDE,
    CONTEXT_SCALE,
    CONTEXT_LABEL,
    CONTEXT_CALL_STATE,
    CONTEXT_CALL_DIRECTION,
    CONTEXT_LOC_ANSWER,
    CONTEXT_ANSWER_REJECT,
    CONTEXT_PASSWORD,
    CONTEXT_APPKEY,
    CONTEXT_DIRECTION,
    CONTEXT_TEXT_TYPE,
    CONTEXT_BAR_TIME, //  Burn after reading time

    CONTEXT_SOURCE_PHONE,//源号码
    CONTEXT_FORWARD_COUNT,//转发次数，仅用于判断是否转发，忽略统计

    CONTENT_FILE_NAME,
    CONTENT_FILE_SIZE,

    CONTEXT_IMAGE_W,   //图片宽
    CONTEXT_IMAGE_H,    //图片高

    CONTEXT_RED_PACKAGE,    //红包金额 单位分
    CONTEXT_RED_TITLE,    //红包标题
    CONTEXT_RED_UUID,    //红包url
    CONTEXT_RED_RECEIVE_NAME,//红包领取者姓名
    CONTEXT_RED_RECEIVE_DONE,//该红包是否被领完

}
