// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YouMai.State.proto

package com.youmai.hxsdk.proto;

public final class YouMaiState {
    private YouMaiState() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface UserStateBroadcastOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserStateBroadcast)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string user_id = 1;</code>
         */
        boolean hasUserId();

        /**
         * <code>optional string user_id = 1;</code>
         */
        String getUserId();

        /**
         * <code>optional string user_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        boolean hasNodeId();

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        int getNodeId();

        /**
         * <code>optional int32 sockfd = 3;</code>
         */
        boolean hasSockfd();

        /**
         * <code>optional int32 sockfd = 3;</code>
         */
        int getSockfd();

        /**
         * <code>optional bool online = 4;</code>
         * <p>
         * <pre>
         * 1:online 0:offline
         * </pre>
         */
        boolean hasOnline();

        /**
         * <code>optional bool online = 4;</code>
         * <p>
         * <pre>
         * 1:online 0:offline
         * </pre>
         */
        boolean getOnline();

        /**
         * <code>optional int64 time = 5;</code>
         * <p>
         * <pre>
         * state change time
         * </pre>
         */
        boolean hasTime();

        /**
         * <code>optional int64 time = 5;</code>
         * <p>
         * <pre>
         * state change time
         * </pre>
         */
        long getTime();

        /**
         * <code>optional int32 version = 6;</code>
         */
        boolean hasVersion();

        /**
         * <code>optional int32 version = 6;</code>
         */
        int getVersion();

        /**
         * <code>optional int32 device_type = 7;</code>
         */
        boolean hasDeviceType();

        /**
         * <code>optional int32 device_type = 7;</code>
         */
        int getDeviceType();
    }

    /**
     * Protobuf type {@code UserStateBroadcast}
     */
    public static final class UserStateBroadcast extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:UserStateBroadcast)
            UserStateBroadcastOrBuilder {
        // Use UserStateBroadcast.newBuilder() to construct.
        private UserStateBroadcast(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private UserStateBroadcast(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final UserStateBroadcast defaultInstance;

        public static UserStateBroadcast getDefaultInstance() {
            return defaultInstance;
        }

        public UserStateBroadcast getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private UserStateBroadcast(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            userId_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            nodeId_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            sockfd_ = input.readInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            online_ = input.readBool();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            time_ = input.readInt64();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            version_ = input.readInt32();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            deviceType_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return YouMaiState.internal_static_com_proto_state_UserStateBroadcast_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return YouMaiState.internal_static_com_proto_state_UserStateBroadcast_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            YouMaiState.UserStateBroadcast.class, YouMaiState.UserStateBroadcast.Builder.class);
        }

        public static com.google.protobuf.Parser<UserStateBroadcast> PARSER =
                new com.google.protobuf.AbstractParser<UserStateBroadcast>() {
                    public UserStateBroadcast parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new UserStateBroadcast(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<UserStateBroadcast> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int USER_ID_FIELD_NUMBER = 1;
        private Object userId_;

        /**
         * <code>optional string user_id = 1;</code>
         */
        public boolean hasUserId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string user_id = 1;</code>
         */
        public String getUserId() {
            Object ref = userId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string user_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            Object ref = userId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NODE_ID_FIELD_NUMBER = 2;
        private int nodeId_;

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        public boolean hasNodeId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        public int getNodeId() {
            return nodeId_;
        }

        public static final int SOCKFD_FIELD_NUMBER = 3;
        private int sockfd_;

        /**
         * <code>optional int32 sockfd = 3;</code>
         */
        public boolean hasSockfd() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int32 sockfd = 3;</code>
         */
        public int getSockfd() {
            return sockfd_;
        }

        public static final int ONLINE_FIELD_NUMBER = 4;
        private boolean online_;

        /**
         * <code>optional bool online = 4;</code>
         * <p>
         * <pre>
         * 1:online 0:offline
         * </pre>
         */
        public boolean hasOnline() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional bool online = 4;</code>
         * <p>
         * <pre>
         * 1:online 0:offline
         * </pre>
         */
        public boolean getOnline() {
            return online_;
        }

        public static final int TIME_FIELD_NUMBER = 5;
        private long time_;

        /**
         * <code>optional int64 time = 5;</code>
         * <p>
         * <pre>
         * state change time
         * </pre>
         */
        public boolean hasTime() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional int64 time = 5;</code>
         * <p>
         * <pre>
         * state change time
         * </pre>
         */
        public long getTime() {
            return time_;
        }

        public static final int VERSION_FIELD_NUMBER = 6;
        private int version_;

        /**
         * <code>optional int32 version = 6;</code>
         */
        public boolean hasVersion() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>optional int32 version = 6;</code>
         */
        public int getVersion() {
            return version_;
        }

        public static final int DEVICE_TYPE_FIELD_NUMBER = 7;
        private int deviceType_;

        /**
         * <code>optional int32 device_type = 7;</code>
         */
        public boolean hasDeviceType() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        /**
         * <code>optional int32 device_type = 7;</code>
         */
        public int getDeviceType() {
            return deviceType_;
        }

        private void initFields() {
            userId_ = "";
            nodeId_ = 0;
            sockfd_ = 0;
            online_ = false;
            time_ = 0L;
            version_ = 0;
            deviceType_ = 0;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, nodeId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, sockfd_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBool(4, online_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt64(5, time_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt32(6, version_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeInt32(7, deviceType_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, nodeId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, sockfd_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, online_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(5, time_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, version_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(7, deviceType_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static YouMaiState.UserStateBroadcast parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static YouMaiState.UserStateBroadcast parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static YouMaiState.UserStateBroadcast parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(YouMaiState.UserStateBroadcast prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code UserStateBroadcast}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserStateBroadcast)
                YouMaiState.UserStateBroadcastOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return YouMaiState.internal_static_com_proto_state_UserStateBroadcast_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return YouMaiState.internal_static_com_proto_state_UserStateBroadcast_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                YouMaiState.UserStateBroadcast.class, YouMaiState.UserStateBroadcast.Builder.class);
            }

            // Construct using YouMaiState.UserStateBroadcast.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                userId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                nodeId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                sockfd_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                online_ = false;
                bitField0_ = (bitField0_ & ~0x00000008);
                time_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000010);
                version_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                deviceType_ = 0;
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return YouMaiState.internal_static_com_proto_state_UserStateBroadcast_descriptor;
            }

            public YouMaiState.UserStateBroadcast getDefaultInstanceForType() {
                return YouMaiState.UserStateBroadcast.getDefaultInstance();
            }

            public YouMaiState.UserStateBroadcast build() {
                YouMaiState.UserStateBroadcast result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public YouMaiState.UserStateBroadcast buildPartial() {
                YouMaiState.UserStateBroadcast result = new YouMaiState.UserStateBroadcast(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.userId_ = userId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.nodeId_ = nodeId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.sockfd_ = sockfd_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.online_ = online_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.time_ = time_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.version_ = version_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.deviceType_ = deviceType_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof YouMaiState.UserStateBroadcast) {
                    return mergeFrom((YouMaiState.UserStateBroadcast) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(YouMaiState.UserStateBroadcast other) {
                if (other == YouMaiState.UserStateBroadcast.getDefaultInstance()) return this;
                if (other.hasUserId()) {
                    bitField0_ |= 0x00000001;
                    userId_ = other.userId_;
                    onChanged();
                }
                if (other.hasNodeId()) {
                    setNodeId(other.getNodeId());
                }
                if (other.hasSockfd()) {
                    setSockfd(other.getSockfd());
                }
                if (other.hasOnline()) {
                    setOnline(other.getOnline());
                }
                if (other.hasTime()) {
                    setTime(other.getTime());
                }
                if (other.hasVersion()) {
                    setVersion(other.getVersion());
                }
                if (other.hasDeviceType()) {
                    setDeviceType(other.getDeviceType());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                YouMaiState.UserStateBroadcast parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (YouMaiState.UserStateBroadcast) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object userId_ = "";

            /**
             * <code>optional string user_id = 1;</code>
             */
            public boolean hasUserId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public String getUserId() {
                Object ref = userId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        userId_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getUserIdBytes() {
                Object ref = userId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder setUserId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder clearUserId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                userId_ = getDefaultInstance().getUserId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder setUserIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userId_ = value;
                onChanged();
                return this;
            }

            private int nodeId_;

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public boolean hasNodeId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public int getNodeId() {
                return nodeId_;
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public Builder setNodeId(int value) {
                bitField0_ |= 0x00000002;
                nodeId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public Builder clearNodeId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                nodeId_ = 0;
                onChanged();
                return this;
            }

            private int sockfd_;

            /**
             * <code>optional int32 sockfd = 3;</code>
             */
            public boolean hasSockfd() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional int32 sockfd = 3;</code>
             */
            public int getSockfd() {
                return sockfd_;
            }

            /**
             * <code>optional int32 sockfd = 3;</code>
             */
            public Builder setSockfd(int value) {
                bitField0_ |= 0x00000004;
                sockfd_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 sockfd = 3;</code>
             */
            public Builder clearSockfd() {
                bitField0_ = (bitField0_ & ~0x00000004);
                sockfd_ = 0;
                onChanged();
                return this;
            }

            private boolean online_;

            /**
             * <code>optional bool online = 4;</code>
             * <p>
             * <pre>
             * 1:online 0:offline
             * </pre>
             */
            public boolean hasOnline() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional bool online = 4;</code>
             * <p>
             * <pre>
             * 1:online 0:offline
             * </pre>
             */
            public boolean getOnline() {
                return online_;
            }

            /**
             * <code>optional bool online = 4;</code>
             * <p>
             * <pre>
             * 1:online 0:offline
             * </pre>
             */
            public Builder setOnline(boolean value) {
                bitField0_ |= 0x00000008;
                online_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool online = 4;</code>
             * <p>
             * <pre>
             * 1:online 0:offline
             * </pre>
             */
            public Builder clearOnline() {
                bitField0_ = (bitField0_ & ~0x00000008);
                online_ = false;
                onChanged();
                return this;
            }

            private long time_;

            /**
             * <code>optional int64 time = 5;</code>
             * <p>
             * <pre>
             * state change time
             * </pre>
             */
            public boolean hasTime() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional int64 time = 5;</code>
             * <p>
             * <pre>
             * state change time
             * </pre>
             */
            public long getTime() {
                return time_;
            }

            /**
             * <code>optional int64 time = 5;</code>
             * <p>
             * <pre>
             * state change time
             * </pre>
             */
            public Builder setTime(long value) {
                bitField0_ |= 0x00000010;
                time_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 time = 5;</code>
             * <p>
             * <pre>
             * state change time
             * </pre>
             */
            public Builder clearTime() {
                bitField0_ = (bitField0_ & ~0x00000010);
                time_ = 0L;
                onChanged();
                return this;
            }

            private int version_;

            /**
             * <code>optional int32 version = 6;</code>
             */
            public boolean hasVersion() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>optional int32 version = 6;</code>
             */
            public int getVersion() {
                return version_;
            }

            /**
             * <code>optional int32 version = 6;</code>
             */
            public Builder setVersion(int value) {
                bitField0_ |= 0x00000020;
                version_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 version = 6;</code>
             */
            public Builder clearVersion() {
                bitField0_ = (bitField0_ & ~0x00000020);
                version_ = 0;
                onChanged();
                return this;
            }

            private int deviceType_;

            /**
             * <code>optional int32 device_type = 7;</code>
             */
            public boolean hasDeviceType() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>optional int32 device_type = 7;</code>
             */
            public int getDeviceType() {
                return deviceType_;
            }

            /**
             * <code>optional int32 device_type = 7;</code>
             */
            public Builder setDeviceType(int value) {
                bitField0_ |= 0x00000040;
                deviceType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 device_type = 7;</code>
             */
            public Builder clearDeviceType() {
                bitField0_ = (bitField0_ & ~0x00000040);
                deviceType_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:UserStateBroadcast)
        }

        static {
            defaultInstance = new UserStateBroadcast(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:UserStateBroadcast)
    }

    public interface UserStateReportOrBuilder extends
            // @@protoc_insertion_point(interface_extends:UserStateReport)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string user_id = 1;</code>
         */
        boolean hasUserId();

        /**
         * <code>optional string user_id = 1;</code>
         */
        String getUserId();

        /**
         * <code>optional string user_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        boolean hasNodeId();

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        int getNodeId();

        /**
         * <code>optional bool online = 3;</code>
         */
        boolean hasOnline();

        /**
         * <code>optional bool online = 3;</code>
         */
        boolean getOnline();
    }

    /**
     * Protobuf type {@code UserStateReport}
     * <p>
     * <pre>
     * busi msg report state to login server
     * </pre>
     */
    public static final class UserStateReport extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:UserStateReport)
            UserStateReportOrBuilder {
        // Use UserStateReport.newBuilder() to construct.
        private UserStateReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private UserStateReport(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final UserStateReport defaultInstance;

        public static UserStateReport getDefaultInstance() {
            return defaultInstance;
        }

        public UserStateReport getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private UserStateReport(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            userId_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            nodeId_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            online_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return YouMaiState.internal_static_com_proto_state_UserStateReport_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return YouMaiState.internal_static_com_proto_state_UserStateReport_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            YouMaiState.UserStateReport.class, YouMaiState.UserStateReport.Builder.class);
        }

        public static com.google.protobuf.Parser<UserStateReport> PARSER =
                new com.google.protobuf.AbstractParser<UserStateReport>() {
                    public UserStateReport parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new UserStateReport(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<UserStateReport> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int USER_ID_FIELD_NUMBER = 1;
        private Object userId_;

        /**
         * <code>optional string user_id = 1;</code>
         */
        public boolean hasUserId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string user_id = 1;</code>
         */
        public String getUserId() {
            Object ref = userId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string user_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            Object ref = userId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NODE_ID_FIELD_NUMBER = 2;
        private int nodeId_;

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        public boolean hasNodeId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int32 node_id = 2;</code>
         */
        public int getNodeId() {
            return nodeId_;
        }

        public static final int ONLINE_FIELD_NUMBER = 3;
        private boolean online_;

        /**
         * <code>optional bool online = 3;</code>
         */
        public boolean hasOnline() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional bool online = 3;</code>
         */
        public boolean getOnline() {
            return online_;
        }

        private void initFields() {
            userId_ = "";
            nodeId_ = 0;
            online_ = false;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, nodeId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBool(3, online_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, nodeId_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, online_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static YouMaiState.UserStateReport parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static YouMaiState.UserStateReport parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static YouMaiState.UserStateReport parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static YouMaiState.UserStateReport parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static YouMaiState.UserStateReport parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static YouMaiState.UserStateReport parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static YouMaiState.UserStateReport parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static YouMaiState.UserStateReport parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static YouMaiState.UserStateReport parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static YouMaiState.UserStateReport parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(YouMaiState.UserStateReport prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code UserStateReport}
         * <p>
         * <pre>
         * busi msg report state to login server
         * </pre>
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:UserStateReport)
                YouMaiState.UserStateReportOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return YouMaiState.internal_static_com_proto_state_UserStateReport_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return YouMaiState.internal_static_com_proto_state_UserStateReport_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                YouMaiState.UserStateReport.class, YouMaiState.UserStateReport.Builder.class);
            }

            // Construct using YouMaiState.UserStateReport.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                userId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                nodeId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                online_ = false;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return YouMaiState.internal_static_com_proto_state_UserStateReport_descriptor;
            }

            public YouMaiState.UserStateReport getDefaultInstanceForType() {
                return YouMaiState.UserStateReport.getDefaultInstance();
            }

            public YouMaiState.UserStateReport build() {
                YouMaiState.UserStateReport result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public YouMaiState.UserStateReport buildPartial() {
                YouMaiState.UserStateReport result = new YouMaiState.UserStateReport(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.userId_ = userId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.nodeId_ = nodeId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.online_ = online_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof YouMaiState.UserStateReport) {
                    return mergeFrom((YouMaiState.UserStateReport) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(YouMaiState.UserStateReport other) {
                if (other == YouMaiState.UserStateReport.getDefaultInstance()) return this;
                if (other.hasUserId()) {
                    bitField0_ |= 0x00000001;
                    userId_ = other.userId_;
                    onChanged();
                }
                if (other.hasNodeId()) {
                    setNodeId(other.getNodeId());
                }
                if (other.hasOnline()) {
                    setOnline(other.getOnline());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                YouMaiState.UserStateReport parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (YouMaiState.UserStateReport) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object userId_ = "";

            /**
             * <code>optional string user_id = 1;</code>
             */
            public boolean hasUserId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public String getUserId() {
                Object ref = userId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        userId_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getUserIdBytes() {
                Object ref = userId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder setUserId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder clearUserId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                userId_ = getDefaultInstance().getUserId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_id = 1;</code>
             */
            public Builder setUserIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userId_ = value;
                onChanged();
                return this;
            }

            private int nodeId_;

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public boolean hasNodeId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public int getNodeId() {
                return nodeId_;
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public Builder setNodeId(int value) {
                bitField0_ |= 0x00000002;
                nodeId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 node_id = 2;</code>
             */
            public Builder clearNodeId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                nodeId_ = 0;
                onChanged();
                return this;
            }

            private boolean online_;

            /**
             * <code>optional bool online = 3;</code>
             */
            public boolean hasOnline() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional bool online = 3;</code>
             */
            public boolean getOnline() {
                return online_;
            }

            /**
             * <code>optional bool online = 3;</code>
             */
            public Builder setOnline(boolean value) {
                bitField0_ |= 0x00000004;
                online_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool online = 3;</code>
             */
            public Builder clearOnline() {
                bitField0_ = (bitField0_ & ~0x00000004);
                online_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:UserStateReport)
        }

        static {
            defaultInstance = new UserStateReport(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:UserStateReport)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_proto_state_UserStateBroadcast_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_proto_state_UserStateBroadcast_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_proto_state_UserStateReport_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_proto_state_UserStateReport_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022YouMai.State.proto\022\017com.proto.state\"\212\001" +
                        "\n\022UserStateBroadcast\022\017\n\007user_id\030\001 \001(\t\022\017\n" +
                        "\007node_id\030\002 \001(\005\022\016\n\006sockfd\030\003 \001(\005\022\016\n\006online" +
                        "\030\004 \001(\010\022\014\n\004time\030\005 \001(\003\022\017\n\007version\030\006 \001(\005\022\023\n" +
                        "\013device_type\030\007 \001(\005\"C\n\017UserStateReport\022\017\n" +
                        "\007user_id\030\001 \001(\t\022\017\n\007node_id\030\002 \001(\005\022\016\n\006onlin" +
                        "e\030\003 \001(\010"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_proto_state_UserStateBroadcast_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_proto_state_UserStateBroadcast_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_com_proto_state_UserStateBroadcast_descriptor,
                new String[]{"UserId", "NodeId", "Sockfd", "Online", "Time", "Version", "DeviceType",});
        internal_static_com_proto_state_UserStateReport_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_proto_state_UserStateReport_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_com_proto_state_UserStateReport_descriptor,
                new String[]{"UserId", "NodeId", "Online",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
