package com.youmai.hxsdk.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.youmai.hxsdk.db.bean.CacheMsgBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CACHE_MSG_BEAN".
*/
public class CacheMsgBeanDao extends AbstractDao<CacheMsgBean, Long> {

    public static final String TABLENAME = "CACHE_MSG_BEAN";

    /**
     * Properties of entity CacheMsgBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MsgId = new Property(1, Long.class, "msgId", false, "MSG_ID");
        public final static Property MsgType = new Property(2, int.class, "msgType", false, "MSG_TYPE");
        public final static Property MsgTime = new Property(3, long.class, "msgTime", false, "MSG_TIME");
        public final static Property SenderUserId = new Property(4, String.class, "senderUserId", false, "SENDER_USER_ID");
        public final static Property SenderMobile = new Property(5, String.class, "senderMobile", false, "SENDER_MOBILE");
        public final static Property SenderSex = new Property(6, String.class, "senderSex", false, "SENDER_SEX");
        public final static Property SenderRealName = new Property(7, String.class, "senderRealName", false, "SENDER_REAL_NAME");
        public final static Property SenderAvatar = new Property(8, String.class, "senderAvatar", false, "SENDER_AVATAR");
        public final static Property SenderUserName = new Property(9, String.class, "senderUserName", false, "SENDER_USER_NAME");
        public final static Property ReceiverUserId = new Property(10, String.class, "receiverUserId", false, "RECEIVER_USER_ID");
        public final static Property ContentJsonBody = new Property(11, String.class, "contentJsonBody", false, "CONTENT_JSON_BODY");
        public final static Property GroupId = new Property(12, int.class, "groupId", false, "GROUP_ID");
        public final static Property GroupType = new Property(13, int.class, "groupType", false, "GROUP_TYPE");
        public final static Property TargetName = new Property(14, String.class, "targetName", false, "TARGET_NAME");
        public final static Property TargetUuid = new Property(15, String.class, "targetUuid", false, "TARGET_UUID");
        public final static Property TargetAvatar = new Property(16, String.class, "targetAvatar", false, "TARGET_AVATAR");
        public final static Property TargetUserName = new Property(17, String.class, "targetUserName", false, "TARGET_USER_NAME");
        public final static Property MsgStatus = new Property(18, int.class, "msgStatus", false, "MSG_STATUS");
        public final static Property Progress = new Property(19, int.class, "progress", false, "PROGRESS");
        public final static Property MemberChanged = new Property(20, String.class, "memberChanged", false, "MEMBER_CHANGED");
    }


    public CacheMsgBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CacheMsgBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CACHE_MSG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MSG_ID\" INTEGER," + // 1: msgId
                "\"MSG_TYPE\" INTEGER NOT NULL ," + // 2: msgType
                "\"MSG_TIME\" INTEGER NOT NULL ," + // 3: msgTime
                "\"SENDER_USER_ID\" TEXT," + // 4: senderUserId
                "\"SENDER_MOBILE\" TEXT," + // 5: senderMobile
                "\"SENDER_SEX\" TEXT," + // 6: senderSex
                "\"SENDER_REAL_NAME\" TEXT," + // 7: senderRealName
                "\"SENDER_AVATAR\" TEXT," + // 8: senderAvatar
                "\"SENDER_USER_NAME\" TEXT," + // 9: senderUserName
                "\"RECEIVER_USER_ID\" TEXT," + // 10: receiverUserId
                "\"CONTENT_JSON_BODY\" TEXT," + // 11: contentJsonBody
                "\"GROUP_ID\" INTEGER NOT NULL ," + // 12: groupId
                "\"GROUP_TYPE\" INTEGER NOT NULL ," + // 13: groupType
                "\"TARGET_NAME\" TEXT," + // 14: targetName
                "\"TARGET_UUID\" TEXT," + // 15: targetUuid
                "\"TARGET_AVATAR\" TEXT," + // 16: targetAvatar
                "\"TARGET_USER_NAME\" TEXT," + // 17: targetUserName
                "\"MSG_STATUS\" INTEGER NOT NULL ," + // 18: msgStatus
                "\"PROGRESS\" INTEGER NOT NULL ," + // 19: progress
                "\"MEMBER_CHANGED\" TEXT);"); // 20: memberChanged
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CACHE_MSG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgTime());
 
        String senderUserId = entity.getSenderUserId();
        if (senderUserId != null) {
            stmt.bindString(5, senderUserId);
        }
 
        String senderMobile = entity.getSenderMobile();
        if (senderMobile != null) {
            stmt.bindString(6, senderMobile);
        }
 
        String senderSex = entity.getSenderSex();
        if (senderSex != null) {
            stmt.bindString(7, senderSex);
        }
 
        String senderRealName = entity.getSenderRealName();
        if (senderRealName != null) {
            stmt.bindString(8, senderRealName);
        }
 
        String senderAvatar = entity.getSenderAvatar();
        if (senderAvatar != null) {
            stmt.bindString(9, senderAvatar);
        }
 
        String senderUserName = entity.getSenderUserName();
        if (senderUserName != null) {
            stmt.bindString(10, senderUserName);
        }
 
        String receiverUserId = entity.getReceiverUserId();
        if (receiverUserId != null) {
            stmt.bindString(11, receiverUserId);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(12, contentJsonBody);
        }
        stmt.bindLong(13, entity.getGroupId());
        stmt.bindLong(14, entity.getGroupType());
 
        String targetName = entity.getTargetName();
        if (targetName != null) {
            stmt.bindString(15, targetName);
        }
 
        String targetUuid = entity.getTargetUuid();
        if (targetUuid != null) {
            stmt.bindString(16, targetUuid);
        }
 
        String targetAvatar = entity.getTargetAvatar();
        if (targetAvatar != null) {
            stmt.bindString(17, targetAvatar);
        }
 
        String targetUserName = entity.getTargetUserName();
        if (targetUserName != null) {
            stmt.bindString(18, targetUserName);
        }
        stmt.bindLong(19, entity.getMsgStatus());
        stmt.bindLong(20, entity.getProgress());
 
        String memberChanged = entity.getMemberChanged();
        if (memberChanged != null) {
            stmt.bindString(21, memberChanged);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CacheMsgBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindLong(2, msgId);
        }
        stmt.bindLong(3, entity.getMsgType());
        stmt.bindLong(4, entity.getMsgTime());
 
        String senderUserId = entity.getSenderUserId();
        if (senderUserId != null) {
            stmt.bindString(5, senderUserId);
        }
 
        String senderMobile = entity.getSenderMobile();
        if (senderMobile != null) {
            stmt.bindString(6, senderMobile);
        }
 
        String senderSex = entity.getSenderSex();
        if (senderSex != null) {
            stmt.bindString(7, senderSex);
        }
 
        String senderRealName = entity.getSenderRealName();
        if (senderRealName != null) {
            stmt.bindString(8, senderRealName);
        }
 
        String senderAvatar = entity.getSenderAvatar();
        if (senderAvatar != null) {
            stmt.bindString(9, senderAvatar);
        }
 
        String senderUserName = entity.getSenderUserName();
        if (senderUserName != null) {
            stmt.bindString(10, senderUserName);
        }
 
        String receiverUserId = entity.getReceiverUserId();
        if (receiverUserId != null) {
            stmt.bindString(11, receiverUserId);
        }
 
        String contentJsonBody = entity.getContentJsonBody();
        if (contentJsonBody != null) {
            stmt.bindString(12, contentJsonBody);
        }
        stmt.bindLong(13, entity.getGroupId());
        stmt.bindLong(14, entity.getGroupType());
 
        String targetName = entity.getTargetName();
        if (targetName != null) {
            stmt.bindString(15, targetName);
        }
 
        String targetUuid = entity.getTargetUuid();
        if (targetUuid != null) {
            stmt.bindString(16, targetUuid);
        }
 
        String targetAvatar = entity.getTargetAvatar();
        if (targetAvatar != null) {
            stmt.bindString(17, targetAvatar);
        }
 
        String targetUserName = entity.getTargetUserName();
        if (targetUserName != null) {
            stmt.bindString(18, targetUserName);
        }
        stmt.bindLong(19, entity.getMsgStatus());
        stmt.bindLong(20, entity.getProgress());
 
        String memberChanged = entity.getMemberChanged();
        if (memberChanged != null) {
            stmt.bindString(21, memberChanged);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CacheMsgBean readEntity(Cursor cursor, int offset) {
        CacheMsgBean entity = new CacheMsgBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // msgId
            cursor.getInt(offset + 2), // msgType
            cursor.getLong(offset + 3), // msgTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // senderUserId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // senderMobile
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // senderSex
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // senderRealName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // senderAvatar
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // senderUserName
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // receiverUserId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // contentJsonBody
            cursor.getInt(offset + 12), // groupId
            cursor.getInt(offset + 13), // groupType
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // targetName
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // targetUuid
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // targetAvatar
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // targetUserName
            cursor.getInt(offset + 18), // msgStatus
            cursor.getInt(offset + 19), // progress
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20) // memberChanged
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CacheMsgBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMsgId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMsgType(cursor.getInt(offset + 2));
        entity.setMsgTime(cursor.getLong(offset + 3));
        entity.setSenderUserId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSenderMobile(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSenderSex(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSenderRealName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSenderAvatar(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSenderUserName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setReceiverUserId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setContentJsonBody(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setGroupId(cursor.getInt(offset + 12));
        entity.setGroupType(cursor.getInt(offset + 13));
        entity.setTargetName(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTargetUuid(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTargetAvatar(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTargetUserName(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setMsgStatus(cursor.getInt(offset + 18));
        entity.setProgress(cursor.getInt(offset + 19));
        entity.setMemberChanged(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CacheMsgBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CacheMsgBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CacheMsgBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
